const constants = {
  ACTUALIZA_GEOM_D3: "ACTUALIZA_GEOM_D3",
  SET_FLOAT_REF_POINT: "SET_FLOAT_REF_POINT",
  ADD_FLOAT_SEGMENT: "ADD_FLOAT_SEGMENT",
  ADD_POINT: "ADD_POINT",
  ADD_SEGMENT: "ADD_SEGMENT",
  ADD_POLYLINE: "ADD_POLYLINE",
  ADD_HATCH: "ADD_HATCH",
  ADD_GROUP: "ADD_GROUP",
  CHECK_GROUPS: "CHECK_GROUPS",
  CALCULA_SECCION: "CALCULA_SECCION",
  SET_MODO: "SET_MODO",
  GET_SELECTION_FROM_EVENT: "GET_SELECTION_FROM_EVENT",
  EDIT_POINT_MOVE: "EDIT_POINT_MOVE",
};

export default constants;